export const ActionType = {
    GET_CATALOG: 'GET_CATALOG',
    GET_CATEGORIES: 'GET_CATEGORIES',
    ADD_TO_CARD: 'ADD_TO_CARD',
    REMOVE_FROM_CARD: 'REMOVE_FROM_CARD',
    DEC_FROM_CART: 'DEC_FROM_CART',

    GET_BASED: 'GET_BASED',

    ADD_TO_FAVORITE: 'ADD_TO_FAVORITE',
    REMOVE_FROM_FAVORITE: 'REMOVE_FROM_FAVORITE',

    GET_ONE_PRODUCT: 'GET_ONE_PRODUCT',
    REMOVE_ONE_PRODUCT: 'REMOVE_ONE_PRODUCT',

    SORT_CATALOG: "SORT_CATALOG",
}